db = db.getSiblingDB("sample_restaurants");

db.food_words.drop();

db.food_words.insertMany([
  {word:"apple"},
  {word:"apricot"},
  {word:"banana"},
  {word:"blackberry"},
  {word:"blackcurrant"},
  {word:"blueberry"},
  {word:"cherry"},
  {word:"coconut"},
  {word:"fig"},
  {word:"gooseberry"},
  {word:"grape"},
  {word:"grapefruit"},
  {word:"kiwi fruit"},
  {word:"lemon"},
  {word:"lime"},
  {word:"mango"},
  {word:"melon"},
  {word:"orange"},
  {word:"peach"},
  {word:"pear"},
  {word:"pineapple"},
  {word:"plum"},
  {word:"pomegranate"},
  {word:"raspberry"},
  {word:"redcurrant"},
  {word:"rhubarb"},
  {word:"strawberry"},
  {word:"artichoke"},
  {word:"asparagus"},
  {word:"aubergine"},
  {word:"avocado"},
  {word:"beansprouts"},
  {word:"beetroot"},
  {word:"broad beans"},
  {word:"broccoli"},
  {word:"brussel sprouts"},
  {word:"cabbage"},
  {word:"carrot"},
  {word:"cauliflower"},
  {word:"celery"},
  {word:"chili pepper"},
  {word:"courgette"},
  {word:"cucumber"},
  {word:"French beans"},
  {word:"garlic"},
  {word:"ginger"},
  {word:"leek"},
  {word:"lettuce"},
  {word:"mushroom"},
  {word:"onion"},
  {word:"peas"},
  {word:"pepper"},
  {word:"potato"},
  {word:"pumpkin"},
  {word:"radish"},
  {word:"rocket"},
  {word:"runner beans"},
  {word:"swede"},
  {word:"sweet potato"},
  {word:"sweetcorn"},
  {word:"tomato"},
  {word:"turnip"},
  {word:"spinach"},
  {word:"spring onion"},
  {word:"squash"},
  {word:"baked beans"},
  {word:"kidney beans"},
  {word:"soup"},
  {word:"chips"},
  {word:"ice cream"},
  {word:"butter"},
  {word:"cream"},
  {word:"cheese"},
  {word:"blue cheese"},
  {word:"cottage cheese"},
  {word:"goats cheese"},
  {word:"crème fraîche"},
  {word:"eggs"},
  {word:"margarine"},
  {word:"milk"},
  {word:"sour cream"},
  {word:"yogurt"},
  {word:"baguette"},
  {word:"bread"},
  {word:"cake"},
  {word:"quiche"},
  {word:"sponge cake"},
  {word:"baking powder"},
  {word:"flour"},
  {word:"cornflour"},
  {word:"sugar"},
  {word:"brown sugar"},
  {word:"icing sugar"},
  {word:"pastry"},
  {word:"yeast"},
  {word:"prunes"},
  {word:"dates"},
  {word:"raisins"},
  {word:"sultanas"},
  {word:"cornflakes"},
  {word:"honey"},
  {word:"jam"},
  {word:"marmalade"},
  {word:"muesli"},
  {word:"porridge"},
  {word:"toast"},
  {word:"noodles"},
  {word:"pasta"},
  {word:"pasta sauce"},
  {word:"pizza"},
  {word:"rice"},
  {word:"spaghetti"},
  {word:"ketchup"},
  {word:"mayonnaise"},
  {word:"mustard"},
  {word:"pepper"},
  {word:"salad dressing"},
  {word:"salt"},
  {word:"vinaigrette"},
  {word:"vinegar"},
  {word:"biscuits"},
  {word:"chocolate"},
  {word:"cookie"},
  {word:"crisps"},
  {word:"hummus"},
  {word:"nuts"},
  {word:"olives"},
  {word:"peanuts"},
  {word:"sweets"},
  {word:"walnuts"},
  {word:"basil"},
  {word:"chives"},
  {word:"coriander"},
  {word:"dill"},
  {word:"parsley"},
  {word:"rosemary"},
  {word:"sage"},
  {word:"thyme"},
  {word:"SPICES"},
  {word:"chili powder"},
  {word:"cinnamon"},
  {word:"cumin"},
  {word:"curry powder"},
  {word:"nutmeg"},
  {word:"paprika"},
  {word:"saffron"}
]);
